/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    herds: Herd;
    animals: Animal;
    calvings: Calving;
    inseminations: Insemination;
    'milk-tests': MilkTest;
    'health-events': HealthEvent;
    'data-submissions': DataSubmission;
    'access-requests': AccessRequest;
    'index-profiles': IndexProfile;
    'index-values': IndexValue;
    'index-bases': IndexBase;
    events: Event;
    documents: Document;
    media: Media;
    breeds: Breed;
    lines: Line;
    'breeding-categories': BreedingCategory;
    'breeding-classes': BreedingClass;
    'animal-purposes': AnimalPurpose;
    'disposal-reasons': DisposalReason;
    'coat-colors': CoatColor;
    'blood-groups': BloodGroup;
    'reproduction-methods': ReproductionMethod;
    'semen-types': SemenType;
    'insemination-results': InseminationResult;
    'dna-test-types': DnaTestType;
    'haplotype-types': HaplotypeType;
    'health-event-types': HealthEventType;
    technicians: Technician;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    herds: HerdsSelect<false> | HerdsSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    calvings: CalvingsSelect<false> | CalvingsSelect<true>;
    inseminations: InseminationsSelect<false> | InseminationsSelect<true>;
    'milk-tests': MilkTestsSelect<false> | MilkTestsSelect<true>;
    'health-events': HealthEventsSelect<false> | HealthEventsSelect<true>;
    'data-submissions': DataSubmissionsSelect<false> | DataSubmissionsSelect<true>;
    'access-requests': AccessRequestsSelect<false> | AccessRequestsSelect<true>;
    'index-profiles': IndexProfilesSelect<false> | IndexProfilesSelect<true>;
    'index-values': IndexValuesSelect<false> | IndexValuesSelect<true>;
    'index-bases': IndexBasesSelect<false> | IndexBasesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    breeds: BreedsSelect<false> | BreedsSelect<true>;
    lines: LinesSelect<false> | LinesSelect<true>;
    'breeding-categories': BreedingCategoriesSelect<false> | BreedingCategoriesSelect<true>;
    'breeding-classes': BreedingClassesSelect<false> | BreedingClassesSelect<true>;
    'animal-purposes': AnimalPurposesSelect<false> | AnimalPurposesSelect<true>;
    'disposal-reasons': DisposalReasonsSelect<false> | DisposalReasonsSelect<true>;
    'coat-colors': CoatColorsSelect<false> | CoatColorsSelect<true>;
    'blood-groups': BloodGroupsSelect<false> | BloodGroupsSelect<true>;
    'reproduction-methods': ReproductionMethodsSelect<false> | ReproductionMethodsSelect<true>;
    'semen-types': SemenTypesSelect<false> | SemenTypesSelect<true>;
    'insemination-results': InseminationResultsSelect<false> | InseminationResultsSelect<true>;
    'dna-test-types': DnaTestTypesSelect<false> | DnaTestTypesSelect<true>;
    'haplotype-types': HaplotypeTypesSelect<false> | HaplotypeTypesSelect<true>;
    'health-event-types': HealthEventTypesSelect<false> | HealthEventTypesSelect<true>;
    technicians: TechniciansSelect<false> | TechniciansSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  lastName: string;
  firstName: string;
  middleName?: string | null;
  role: 'farmer' | 'service' | 'individual' | 'admin';
  phone?: string | null;
  /**
   * Хозяйство или сервисная организация, к которой привязан пользователь
   */
  organization?: (number | null) | Organization;
  position?: string | null;
  confirmed?: boolean | null;
  acceptedPolicy?: boolean | null;
  notifySubmissions?: boolean | null;
  notifyTrust?: boolean | null;
  notifyNews?: boolean | null;
  notifySeenAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  shortName?: string | null;
  type?: ('farm' | 'service' | 'individual') | null;
  inn?: string | null;
  kpp?: string | null;
  ogrn?: string | null;
  region?:
    | (
        | 'Самарская область'
        | 'Московская область'
        | 'Ленинградская область'
        | 'Краснодарский край'
        | 'Красноярский край'
        | 'Республика Татарстан'
        | 'Свердловская область'
        | 'Воронежская область'
        | 'Кировская область'
        | 'Удмуртская Республика'
      )
    | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  membership?: ('none' | 'pending' | 'member') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herds".
 */
export interface Herd {
  id: number;
  name: string;
  code?: string | null;
  organization: number | Organization;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  /**
   * Присваивается автоматически при создании и никогда не меняется
   */
  uuid?: string | null;
  identNumber: string;
  idFormat?: ('rf' | 'icar' | 'usa' | 'can' | 'deu' | 'internal') | null;
  name?: string | null;
  /**
   * Транслитерация по ГОСТ 7.79-2000 (ISO-9), заполняется автоматически
   */
  nameLatin?: string | null;
  altIds?: {
    isoId?: string | null;
    internationalId?: string | null;
    earTag?: string | null;
    inventoryNumber?: string | null;
    chipNumber?: string | null;
    chipDate?: string | null;
    gpkMark?: string | null;
    gpkNumber?: string | null;
  };
  kind?: ('cow' | 'bull' | 'heifer' | 'calf') | null;
  sex: 'female' | 'male';
  state?: ('alive' | 'sold' | 'culled' | 'dead') | null;
  ageGroup?: ('calf' | 'heifer' | 'firstCalf' | 'cow2' | 'cow3' | 'bull') | null;
  birthDate?: string | null;
  breed?: (number | null) | Breed;
  bloodPercent?: number | null;
  improvers?: {
    breed1?: (number | null) | Breed;
    share1?: number | null;
    breed2?: (number | null) | Breed;
    share2?: number | null;
  };
  coatColor?: (number | null) | CoatColor;
  bloodGroup?: (number | null) | BloodGroup;
  purpose?: (number | null) | AnimalPurpose;
  owner: number | Organization;
  herd?: (number | null) | Herd;
  author?: (number | null) | User;
  /**
   * ТЗ, Таблица №4: −1 отклонено, 0 черновик, 1 проверено собственником, 2 подтверждено лабораторией, 3 верифицировано ассоциацией
   */
  trustLevel?: number | null;
  trustCheckedAt?: string | null;
  publicVisible?: boolean | null;
  publicDetails?: boolean | null;
  photo?: (number | null) | Media;
  notes?: string | null;
  forSale?: boolean | null;
  /**
   * Итоговое значение, выводится в таблице поиска
   */
  ipc?: number | null;
  ipcRank?: number | null;
  ipcDetails?: {
    forecast?: number | null;
    r?: number | null;
    percentile?: number | null;
  };
  evaluationDate?: string | null;
  production?: {
    reliabilityLevel?: number | null;
    milk?: {
      forecast?: number | null;
      r?: number | null;
    };
    fatPercent?: {
      forecast?: number | null;
      r?: number | null;
    };
    proteinPercent?: {
      forecast?: number | null;
      r?: number | null;
    };
    fatKg?: {
      forecast?: number | null;
      r?: number | null;
    };
    proteinKg?: {
      forecast?: number | null;
      r?: number | null;
    };
    productionIndex?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  reproduction?: {
    fertility?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  health?: {
    reliabilityLevel?: number | null;
    productiveLongevity?: {
      forecast?: number | null;
      r?: number | null;
    };
    udderHealth?: {
      forecast?: number | null;
      r?: number | null;
    };
    calfMortality?: {
      forecast?: number | null;
      r?: number | null;
    };
    calvingEase?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  exterior?: {
    height?: number | null;
    chestWidth?: number | null;
    bodyDepth?: number | null;
    bodyType?: number | null;
    rumpAngle?: number | null;
    rumpWidth?: number | null;
    rearLegsRear?: number | null;
    rearLegsSide?: number | null;
    hoofAngle?: number | null;
    frontLegs?: number | null;
    movement?: number | null;
    foreUdder?: number | null;
    frontTeatPlacement?: number | null;
    teatLength?: number | null;
    udderDepth?: number | null;
    rearUdder?: number | null;
    centralLigament?: number | null;
    rearTeatPlacement?: number | null;
    bodyComposite?: number | null;
    udderComposite?: number | null;
    legsComposite?: number | null;
  };
  /**
   * Значения последней завершённой лактации
   */
  summary?: {
    milkYield?: number | null;
    fatPercent?: number | null;
    proteinPercent?: number | null;
    fatKg?: number | null;
    proteinKg?: number | null;
    fatProteinSum?: number | null;
    milkRank?: number | null;
  };
  lactations?:
    | {
        number?: number | null;
        calvingDate?: string | null;
        inseminationDate?: string | null;
        serviceBull?: string | null;
        dd?: number | null;
        milkYield?: number | null;
        milk305?: number | null;
        fat305?: number | null;
        protein305?: number | null;
        scc?: number | null;
        dryOffDate?: string | null;
        fatKg?: number | null;
        proteinKg?: number | null;
        endDate?: string | null;
        id?: string | null;
      }[]
    | null;
  category?: (number | null) | BreedingCategory;
  /**
   * ТЗ, п. 1.5. Печатается в свидетельстве: «Племенная книга, категория II: внесено по продуктивности»
   */
  registrationBasis?: ('origin' | 'productivity') | null;
  breedingClass?: (number | null) | BreedingClass;
  father?: (number | null) | Animal;
  mother?: (number | null) | Animal;
  line?: (number | null) | Line;
  family?: (number | null) | Line;
  pedigreeText?: {
    fatherId?: string | null;
    fatherName?: string | null;
    motherId?: string | null;
    motherName?: string | null;
    fatherFatherId?: string | null;
    motherFatherId?: string | null;
  };
  inbreeding?: number | null;
  inbreedingNeedsApproval?: boolean | null;
  genetics?: {
    /**
     * Комплексная вертебральная малформация
     */
    cvm?: ('unknown' | 'free' | 'carrier') | null;
    /**
     * Наследственный иммунодефицит
     */
    blad?: ('unknown' | 'free' | 'carrier') | null;
    dumps?: ('unknown' | 'free' | 'carrier') | null;
    kappaCasein?: string | null;
    betaCasein?: string | null;
    betaLactoglobulin?: string | null;
  };
  haplotypes?:
    | {
        type?: (number | null) | HaplotypeType;
        status?: ('unknown' | 'free' | 'carrier') | null;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  dnaTests?:
    | {
        type?: (number | null) | DnaTestType;
        date?: string | null;
        laboratory?: (number | null) | Organization;
        result?: string | null;
        file?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  arrivalDate?: string | null;
  previousOrganization?: (number | null) | Organization;
  disposalDate?: string | null;
  disposalReason?: (number | null) | DisposalReason;
  disposalOrganization?: (number | null) | Organization;
  /**
   * ТЗ, стр. 43: данные животных никогда не удаляются — только перевод в архив
   */
  archived?: boolean | null;
  archiveReason?: string | null;
  lastEditUser?: (number | null) | User;
  lastEditTime?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NPOR» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds".
 */
export interface Breed {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  /**
   * Трёхбуквенный код: HOL — голштинская, JER — джерсейская
   */
  whffCode?: string | null;
  isImprover?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NMAST» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coat-colors".
 */
export interface CoatColor {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «GRUPPA_KRO» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blood-groups".
 */
export interface BloodGroup {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NNAZNACH» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-purposes".
 */
export interface AnimalPurpose {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Соответствует полю «NKAT» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeding-categories".
 */
export interface BreedingCategory {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  /**
   * Отмечается для категории II — животное внесено по продуктивности (ТЗ, п. 1.5)
   */
  allowsIncompletePedigree?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NKKLASS» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeding-classes".
 */
export interface BreedingClass {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NLIN / NVETKA / FAMILY» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lines".
 */
export interface Line {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  kind?: ('line' | 'branch' | 'family') | null;
  parentLine?: (number | null) | Line;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "haplotype-types".
 */
export interface HaplotypeType {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dna-test-types".
 */
export interface DnaTestType {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  markerKind?: ('genetic-defect' | 'protein' | 'parentage' | 'genomic-evaluation') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NPV» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disposal-reasons".
 */
export interface DisposalReason {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calvings".
 */
export interface Calving {
  id: number;
  animal: number | Animal;
  number: number;
  date: string;
  result?: ('heifer' | 'bull' | 'twins' | 'stillborn' | 'abortion') | null;
  milkingDays?: number | null;
  dryOffDate?: string | null;
  ease?: ('easy' | 'assisted' | 'hard') | null;
  calfWeight?: number | null;
  calves?: (number | Animal)[] | null;
  comment?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inseminations".
 */
export interface Insemination {
  id: number;
  animal: number | Animal;
  /**
   * К какому отёлу относится осеменение
   */
  lactationNumber?: number | null;
  date: string;
  bull?: (number | null) | Animal;
  semenType?: (number | null) | SemenType;
  method?: (number | null) | ReproductionMethod;
  doses?: number | null;
  attemptNumber?: number | null;
  technician?: (number | null) | Technician;
  result?: (number | null) | InseminationResult;
  pregnancyCheckDate?: string | null;
  comment?: string | null;
  source?: ('manual' | 'import' | 'api') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NTIP_SPERM» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semen-types".
 */
export interface SemenType {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NRIP» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reproduction-methods".
 */
export interface ReproductionMethod {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NTEXN» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians".
 */
export interface Technician {
  id: number;
  fullName: string;
  certificateNumber?: string | null;
  organization?: (number | null) | Organization;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Соответствует полю «NREZOT» в ИАС «Селэкс»
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insemination-results".
 */
export interface InseminationResult {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milk-tests".
 */
export interface MilkTest {
  id: number;
  animal: number | Animal;
  date: string;
  lactationNumber?: number | null;
  dailyYield: number;
  fatPercent?: number | null;
  proteinPercent?: number | null;
  somaticCells?: number | null;
  laboratory?: (number | null) | Organization;
  source?: ('lab' | 'owner' | 'import' | 'api') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-events".
 */
export interface HealthEvent {
  id: number;
  animal: number | Animal;
  type: number | HealthEventType;
  date: string;
  title?: string | null;
  severity?: ('mild' | 'moderate' | 'severe') | null;
  startDate?: string | null;
  endDate?: string | null;
  excludeFromAnalytics?: boolean | null;
  description?: string | null;
  reportedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-event-types".
 */
export interface HealthEventType {
  id: number;
  /**
   * Короткое обозначение или числовой код из «Селэкс»
   */
  code: string;
  name: string;
  /**
   * Чем меньше, тем выше в списках
   */
  sortOrder?: number | null;
  description?: string | null;
  /**
   * Снимите галочку, чтобы скрыть из выпадающих списков
   */
  isActive?: boolean | null;
  /**
   * Периоды таких событий могут исключаться из расчётов (ТЗ, п. 5.6, требование №4)
   */
  affectsProductivity?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-submissions".
 */
export interface DataSubmission {
  id: number;
  /**
   * Присваивается автоматически
   */
  number?: string | null;
  kind: 'events' | 'animals' | 'productivity' | 'genomics';
  status: 'uploaded' | 'checking' | 'checked' | 'accepted' | 'rejected';
  organization?: (number | null) | Organization;
  submittedBy?: (number | null) | User;
  submittedAt?: string | null;
  sourceFile?: (number | null) | Media;
  review?: {
    checkedBy?: (number | null) | User;
    checkedAt?: string | null;
    /**
     * Например: «Все данные прошли успешную проверку» или «Часть данных не прошла проверку»
     */
    comment?: string | null;
    totalRows?: number | null;
    acceptedRows?: number | null;
    rejectedRows?: number | null;
    /**
     * XLSX-файл со списком строк, не прошедших проверку
     */
    errorProtocol?: (number | null) | Media;
  };
  consent?: {
    agreed?: boolean | null;
    agreedAt?: string | null;
    publishedAt?: string | null;
  };
  history?:
    | {
        at?: string | null;
        status?: ('uploaded' | 'checking' | 'checked' | 'accepted' | 'rejected') | null;
        actor?: (number | null) | User;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests".
 */
export interface AccessRequest {
  id: number;
  animal: number | Animal;
  /**
   * Заполняется по животному
   */
  owner?: (number | null) | Organization;
  requester?: (number | null) | User;
  requesterOrg?: (number | null) | Organization;
  purpose: 'purchase' | 'semen' | 'mating' | 'verification' | 'research' | 'other';
  status: 'new' | 'approved' | 'declined';
  /**
   * Что именно нужно посмотреть и зачем
   */
  comment?: string | null;
  response?: string | null;
  decidedAt?: string | null;
  decidedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-profiles".
 */
export interface IndexProfile {
  id: number;
  name: string;
  kind: 'selection' | 'economic';
  /**
   * Одна фраза: какое узкое место хозяйства он закрывает
   */
  hint?: string | null;
  /**
   * Пусто — стандартный профиль Ассоциации, виден всем
   */
  organization?: (number | null) | Organization;
  isDefault?: boolean | null;
  weights?:
    | {
        trait:
          | 'milk'
          | 'fatKg'
          | 'proteinKg'
          | 'productiveLongevity'
          | 'udderHealth'
          | 'fertility'
          | 'calvingEase'
          | 'calfMortality'
          | 'bodyComposite'
          | 'udderComposite'
          | 'legsComposite';
        /**
         * Для селекционных — проценты влияния (отрицательные допустимы), для экономических — рублей на единицу
         */
        weight: number;
        id?: string | null;
      }[]
    | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-values".
 */
export interface IndexValue {
  id: number;
  animal: number | Animal;
  profileKey: string;
  profileName?: string | null;
  kind?: ('selection' | 'economic') | null;
  weights?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  baseVersion?: string | null;
  value: number;
  reliability?: number | null;
  used?: number | null;
  computedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-bases".
 */
export interface IndexBase {
  id: number;
  /**
   * Например, АПГ-2026-08 — попадает в каждое рассчитанное значение
   */
  version: string;
  source?: ('own' | 'borrowed') | null;
  note?: string | null;
  isActive?: boolean | null;
  animalsUsed?: number | null;
  computedAt?: string | null;
  traits?:
    | {
        trait:
          | 'milk'
          | 'fatKg'
          | 'proteinKg'
          | 'productiveLongevity'
          | 'udderHealth'
          | 'fertility'
          | 'calvingEase'
          | 'calfMortality'
          | 'bodyComposite'
          | 'udderComposite'
          | 'legsComposite';
        mean: number;
        sd: number;
        sdObserved?: number | null;
        meanR?: number | null;
        /**
         * По скольким животным посчитано
         */
        n?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'calving' | 'insemination' | 'dryOff' | 'milkTest' | 'exteriorScore' | 'vetTreatment' | 'move' | 'disposal';
  date: string;
  animal: number | Animal;
  title?: string | null;
  value?: number | null;
  comment?: string | null;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected') | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type?: ('pedigreeCertificate' | 'genotypeReport' | 'vetCertificate' | 'saleContract' | 'other') | null;
  number?: string | null;
  issuedAt?: string | null;
  animal?: (number | null) | Animal;
  organization?: (number | null) | Organization;
  file?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'herds';
        value: number | Herd;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null)
    | ({
        relationTo: 'calvings';
        value: number | Calving;
      } | null)
    | ({
        relationTo: 'inseminations';
        value: number | Insemination;
      } | null)
    | ({
        relationTo: 'milk-tests';
        value: number | MilkTest;
      } | null)
    | ({
        relationTo: 'health-events';
        value: number | HealthEvent;
      } | null)
    | ({
        relationTo: 'data-submissions';
        value: number | DataSubmission;
      } | null)
    | ({
        relationTo: 'access-requests';
        value: number | AccessRequest;
      } | null)
    | ({
        relationTo: 'index-profiles';
        value: number | IndexProfile;
      } | null)
    | ({
        relationTo: 'index-values';
        value: number | IndexValue;
      } | null)
    | ({
        relationTo: 'index-bases';
        value: number | IndexBase;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'breeds';
        value: number | Breed;
      } | null)
    | ({
        relationTo: 'lines';
        value: number | Line;
      } | null)
    | ({
        relationTo: 'breeding-categories';
        value: number | BreedingCategory;
      } | null)
    | ({
        relationTo: 'breeding-classes';
        value: number | BreedingClass;
      } | null)
    | ({
        relationTo: 'animal-purposes';
        value: number | AnimalPurpose;
      } | null)
    | ({
        relationTo: 'disposal-reasons';
        value: number | DisposalReason;
      } | null)
    | ({
        relationTo: 'coat-colors';
        value: number | CoatColor;
      } | null)
    | ({
        relationTo: 'blood-groups';
        value: number | BloodGroup;
      } | null)
    | ({
        relationTo: 'reproduction-methods';
        value: number | ReproductionMethod;
      } | null)
    | ({
        relationTo: 'semen-types';
        value: number | SemenType;
      } | null)
    | ({
        relationTo: 'insemination-results';
        value: number | InseminationResult;
      } | null)
    | ({
        relationTo: 'dna-test-types';
        value: number | DnaTestType;
      } | null)
    | ({
        relationTo: 'haplotype-types';
        value: number | HaplotypeType;
      } | null)
    | ({
        relationTo: 'health-event-types';
        value: number | HealthEventType;
      } | null)
    | ({
        relationTo: 'technicians';
        value: number | Technician;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  lastName?: T;
  firstName?: T;
  middleName?: T;
  role?: T;
  phone?: T;
  organization?: T;
  position?: T;
  confirmed?: T;
  acceptedPolicy?: T;
  notifySubmissions?: T;
  notifyTrust?: T;
  notifyNews?: T;
  notifySeenAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  type?: T;
  inn?: T;
  kpp?: T;
  ogrn?: T;
  region?: T;
  phone?: T;
  email?: T;
  address?: T;
  membership?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herds_select".
 */
export interface HerdsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  organization?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  uuid?: T;
  identNumber?: T;
  idFormat?: T;
  name?: T;
  nameLatin?: T;
  altIds?:
    | T
    | {
        isoId?: T;
        internationalId?: T;
        earTag?: T;
        inventoryNumber?: T;
        chipNumber?: T;
        chipDate?: T;
        gpkMark?: T;
        gpkNumber?: T;
      };
  kind?: T;
  sex?: T;
  state?: T;
  ageGroup?: T;
  birthDate?: T;
  breed?: T;
  bloodPercent?: T;
  improvers?:
    | T
    | {
        breed1?: T;
        share1?: T;
        breed2?: T;
        share2?: T;
      };
  coatColor?: T;
  bloodGroup?: T;
  purpose?: T;
  owner?: T;
  herd?: T;
  author?: T;
  trustLevel?: T;
  trustCheckedAt?: T;
  publicVisible?: T;
  publicDetails?: T;
  photo?: T;
  notes?: T;
  forSale?: T;
  ipc?: T;
  ipcRank?: T;
  ipcDetails?:
    | T
    | {
        forecast?: T;
        r?: T;
        percentile?: T;
      };
  evaluationDate?: T;
  production?:
    | T
    | {
        reliabilityLevel?: T;
        milk?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        fatPercent?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        proteinPercent?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        fatKg?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        proteinKg?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        productionIndex?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  reproduction?:
    | T
    | {
        fertility?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  health?:
    | T
    | {
        reliabilityLevel?: T;
        productiveLongevity?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        udderHealth?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        calfMortality?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        calvingEase?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  exterior?:
    | T
    | {
        height?: T;
        chestWidth?: T;
        bodyDepth?: T;
        bodyType?: T;
        rumpAngle?: T;
        rumpWidth?: T;
        rearLegsRear?: T;
        rearLegsSide?: T;
        hoofAngle?: T;
        frontLegs?: T;
        movement?: T;
        foreUdder?: T;
        frontTeatPlacement?: T;
        teatLength?: T;
        udderDepth?: T;
        rearUdder?: T;
        centralLigament?: T;
        rearTeatPlacement?: T;
        bodyComposite?: T;
        udderComposite?: T;
        legsComposite?: T;
      };
  summary?:
    | T
    | {
        milkYield?: T;
        fatPercent?: T;
        proteinPercent?: T;
        fatKg?: T;
        proteinKg?: T;
        fatProteinSum?: T;
        milkRank?: T;
      };
  lactations?:
    | T
    | {
        number?: T;
        calvingDate?: T;
        inseminationDate?: T;
        serviceBull?: T;
        dd?: T;
        milkYield?: T;
        milk305?: T;
        fat305?: T;
        protein305?: T;
        scc?: T;
        dryOffDate?: T;
        fatKg?: T;
        proteinKg?: T;
        endDate?: T;
        id?: T;
      };
  category?: T;
  registrationBasis?: T;
  breedingClass?: T;
  father?: T;
  mother?: T;
  line?: T;
  family?: T;
  pedigreeText?:
    | T
    | {
        fatherId?: T;
        fatherName?: T;
        motherId?: T;
        motherName?: T;
        fatherFatherId?: T;
        motherFatherId?: T;
      };
  inbreeding?: T;
  inbreedingNeedsApproval?: T;
  genetics?:
    | T
    | {
        cvm?: T;
        blad?: T;
        dumps?: T;
        kappaCasein?: T;
        betaCasein?: T;
        betaLactoglobulin?: T;
      };
  haplotypes?:
    | T
    | {
        type?: T;
        status?: T;
        date?: T;
        id?: T;
      };
  dnaTests?:
    | T
    | {
        type?: T;
        date?: T;
        laboratory?: T;
        result?: T;
        file?: T;
        id?: T;
      };
  arrivalDate?: T;
  previousOrganization?: T;
  disposalDate?: T;
  disposalReason?: T;
  disposalOrganization?: T;
  archived?: T;
  archiveReason?: T;
  lastEditUser?: T;
  lastEditTime?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "calvings_select".
 */
export interface CalvingsSelect<T extends boolean = true> {
  animal?: T;
  number?: T;
  date?: T;
  result?: T;
  milkingDays?: T;
  dryOffDate?: T;
  ease?: T;
  calfWeight?: T;
  calves?: T;
  comment?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inseminations_select".
 */
export interface InseminationsSelect<T extends boolean = true> {
  animal?: T;
  lactationNumber?: T;
  date?: T;
  bull?: T;
  semenType?: T;
  method?: T;
  doses?: T;
  attemptNumber?: T;
  technician?: T;
  result?: T;
  pregnancyCheckDate?: T;
  comment?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milk-tests_select".
 */
export interface MilkTestsSelect<T extends boolean = true> {
  animal?: T;
  date?: T;
  lactationNumber?: T;
  dailyYield?: T;
  fatPercent?: T;
  proteinPercent?: T;
  somaticCells?: T;
  laboratory?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-events_select".
 */
export interface HealthEventsSelect<T extends boolean = true> {
  animal?: T;
  type?: T;
  date?: T;
  title?: T;
  severity?: T;
  startDate?: T;
  endDate?: T;
  excludeFromAnalytics?: T;
  description?: T;
  reportedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "data-submissions_select".
 */
export interface DataSubmissionsSelect<T extends boolean = true> {
  number?: T;
  kind?: T;
  status?: T;
  organization?: T;
  submittedBy?: T;
  submittedAt?: T;
  sourceFile?: T;
  review?:
    | T
    | {
        checkedBy?: T;
        checkedAt?: T;
        comment?: T;
        totalRows?: T;
        acceptedRows?: T;
        rejectedRows?: T;
        errorProtocol?: T;
      };
  consent?:
    | T
    | {
        agreed?: T;
        agreedAt?: T;
        publishedAt?: T;
      };
  history?:
    | T
    | {
        at?: T;
        status?: T;
        actor?: T;
        note?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "access-requests_select".
 */
export interface AccessRequestsSelect<T extends boolean = true> {
  animal?: T;
  owner?: T;
  requester?: T;
  requesterOrg?: T;
  purpose?: T;
  status?: T;
  comment?: T;
  response?: T;
  decidedAt?: T;
  decidedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-profiles_select".
 */
export interface IndexProfilesSelect<T extends boolean = true> {
  name?: T;
  kind?: T;
  hint?: T;
  organization?: T;
  isDefault?: T;
  weights?:
    | T
    | {
        trait?: T;
        weight?: T;
        id?: T;
      };
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-values_select".
 */
export interface IndexValuesSelect<T extends boolean = true> {
  animal?: T;
  profileKey?: T;
  profileName?: T;
  kind?: T;
  weights?: T;
  baseVersion?: T;
  value?: T;
  reliability?: T;
  used?: T;
  computedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "index-bases_select".
 */
export interface IndexBasesSelect<T extends boolean = true> {
  version?: T;
  source?: T;
  note?: T;
  isActive?: T;
  animalsUsed?: T;
  computedAt?: T;
  traits?:
    | T
    | {
        trait?: T;
        mean?: T;
        sd?: T;
        sdObserved?: T;
        meanR?: T;
        n?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  date?: T;
  animal?: T;
  title?: T;
  value?: T;
  comment?: T;
  status?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  number?: T;
  issuedAt?: T;
  animal?: T;
  organization?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeds_select".
 */
export interface BreedsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  whffCode?: T;
  isImprover?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lines_select".
 */
export interface LinesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  kind?: T;
  parentLine?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeding-categories_select".
 */
export interface BreedingCategoriesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  allowsIncompletePedigree?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "breeding-classes_select".
 */
export interface BreedingClassesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animal-purposes_select".
 */
export interface AnimalPurposesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "disposal-reasons_select".
 */
export interface DisposalReasonsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "coat-colors_select".
 */
export interface CoatColorsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blood-groups_select".
 */
export interface BloodGroupsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reproduction-methods_select".
 */
export interface ReproductionMethodsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "semen-types_select".
 */
export interface SemenTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insemination-results_select".
 */
export interface InseminationResultsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dna-test-types_select".
 */
export interface DnaTestTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  markerKind?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "haplotype-types_select".
 */
export interface HaplotypeTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "health-event-types_select".
 */
export interface HealthEventTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  sortOrder?: T;
  description?: T;
  isActive?: T;
  affectsProductivity?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "technicians_select".
 */
export interface TechniciansSelect<T extends boolean = true> {
  fullName?: T;
  certificateNumber?: T;
  organization?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}