/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    organizations: Organization;
    herds: Herd;
    animals: Animal;
    events: Event;
    documents: Document;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    organizations: OrganizationsSelect<false> | OrganizationsSelect<true>;
    herds: HerdsSelect<false> | HerdsSelect<true>;
    animals: AnimalsSelect<false> | AnimalsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  lastName: string;
  firstName: string;
  middleName?: string | null;
  role: 'farmer' | 'service' | 'individual' | 'admin';
  phone?: string | null;
  /**
   * Хозяйство или сервисная организация, к которой привязан пользователь
   */
  organization?: (number | null) | Organization;
  position?: string | null;
  confirmed?: boolean | null;
  acceptedPolicy?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations".
 */
export interface Organization {
  id: number;
  name: string;
  shortName?: string | null;
  type?: ('farm' | 'service' | 'individual') | null;
  inn?: string | null;
  kpp?: string | null;
  ogrn?: string | null;
  region?:
    | (
        | 'Самарская область'
        | 'Московская область'
        | 'Ленинградская область'
        | 'Краснодарский край'
        | 'Красноярский край'
        | 'Республика Татарстан'
        | 'Свердловская область'
        | 'Воронежская область'
        | 'Кировская область'
        | 'Удмуртская Республика'
      )
    | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  membership?: ('none' | 'pending' | 'member') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herds".
 */
export interface Herd {
  id: number;
  name: string;
  code?: string | null;
  organization: number | Organization;
  address?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals".
 */
export interface Animal {
  id: number;
  identNumber: string;
  idFormat?: ('rf' | 'icar' | 'usa' | 'can' | 'deu' | 'internal') | null;
  name?: string | null;
  kind?: ('cow' | 'bull' | 'heifer' | 'calf') | null;
  sex: 'female' | 'male';
  state?: ('alive' | 'sold' | 'culled' | 'dead') | null;
  ageGroup?: ('calf' | 'heifer' | 'firstCalf' | 'cow2' | 'cow3' | 'bull') | null;
  birthDate?: string | null;
  breed?: string | null;
  bloodPercent?: number | null;
  owner: number | Organization;
  herd?: (number | null) | Herd;
  author?: (number | null) | User;
  publicVisible?: boolean | null;
  publicDetails?: boolean | null;
  photo?: (number | null) | Media;
  notes?: string | null;
  /**
   * Итоговое значение, выводится в таблице поиска
   */
  ipc?: number | null;
  ipcDetails?: {
    forecast?: number | null;
    r?: number | null;
    percentile?: number | null;
  };
  evaluationDate?: string | null;
  production?: {
    reliabilityLevel?: number | null;
    milk?: {
      forecast?: number | null;
      r?: number | null;
    };
    fatPercent?: {
      forecast?: number | null;
      r?: number | null;
    };
    proteinPercent?: {
      forecast?: number | null;
      r?: number | null;
    };
    fatKg?: {
      forecast?: number | null;
      r?: number | null;
    };
    proteinKg?: {
      forecast?: number | null;
      r?: number | null;
    };
    productionIndex?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  reproduction?: {
    fertility?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  health?: {
    reliabilityLevel?: number | null;
    productiveLongevity?: {
      forecast?: number | null;
      r?: number | null;
    };
    udderHealth?: {
      forecast?: number | null;
      r?: number | null;
    };
    calfMortality?: {
      forecast?: number | null;
      r?: number | null;
    };
    calvingEase?: {
      forecast?: number | null;
      r?: number | null;
    };
  };
  exterior?: {
    height?: number | null;
    chestWidth?: number | null;
    bodyDepth?: number | null;
    bodyType?: number | null;
    rumpAngle?: number | null;
    rumpWidth?: number | null;
    rearLegsRear?: number | null;
    rearLegsSide?: number | null;
    hoofAngle?: number | null;
    frontLegs?: number | null;
    movement?: number | null;
    foreUdder?: number | null;
    frontTeatPlacement?: number | null;
    teatLength?: number | null;
    udderDepth?: number | null;
    rearUdder?: number | null;
    centralLigament?: number | null;
    rearTeatPlacement?: number | null;
    bodyComposite?: number | null;
    udderComposite?: number | null;
    legsComposite?: number | null;
  };
  /**
   * Значения последней завершённой лактации
   */
  summary?: {
    milkYield?: number | null;
    fatPercent?: number | null;
    proteinPercent?: number | null;
    fatKg?: number | null;
    proteinKg?: number | null;
    fatProteinSum?: number | null;
  };
  lactations?:
    | {
        number?: number | null;
        calvingDate?: string | null;
        inseminationDate?: string | null;
        serviceBull?: string | null;
        dd?: number | null;
        milkYield?: number | null;
        milk305?: number | null;
        fat305?: number | null;
        protein305?: number | null;
        scc?: number | null;
        dryOffDate?: string | null;
        id?: string | null;
      }[]
    | null;
  father?: (number | null) | Animal;
  mother?: (number | null) | Animal;
  pedigreeText?: {
    fatherId?: string | null;
    fatherName?: string | null;
    motherId?: string | null;
    motherName?: string | null;
    fatherFatherId?: string | null;
    motherFatherId?: string | null;
  };
  inbreeding?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  type: 'calving' | 'insemination' | 'dryOff' | 'milkTest' | 'exteriorScore' | 'vetTreatment' | 'move' | 'disposal';
  date: string;
  animal: number | Animal;
  title?: string | null;
  value?: number | null;
  comment?: string | null;
  status?: ('draft' | 'sent' | 'accepted' | 'rejected') | null;
  author?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  title: string;
  type?: ('pedigreeCertificate' | 'genotypeReport' | 'vetCertificate' | 'saleContract' | 'other') | null;
  number?: string | null;
  issuedAt?: string | null;
  animal?: (number | null) | Animal;
  organization?: (number | null) | Organization;
  file?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'organizations';
        value: number | Organization;
      } | null)
    | ({
        relationTo: 'herds';
        value: number | Herd;
      } | null)
    | ({
        relationTo: 'animals';
        value: number | Animal;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  lastName?: T;
  firstName?: T;
  middleName?: T;
  role?: T;
  phone?: T;
  organization?: T;
  position?: T;
  confirmed?: T;
  acceptedPolicy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organizations_select".
 */
export interface OrganizationsSelect<T extends boolean = true> {
  name?: T;
  shortName?: T;
  type?: T;
  inn?: T;
  kpp?: T;
  ogrn?: T;
  region?: T;
  phone?: T;
  email?: T;
  address?: T;
  membership?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "herds_select".
 */
export interface HerdsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  organization?: T;
  address?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "animals_select".
 */
export interface AnimalsSelect<T extends boolean = true> {
  identNumber?: T;
  idFormat?: T;
  name?: T;
  kind?: T;
  sex?: T;
  state?: T;
  ageGroup?: T;
  birthDate?: T;
  breed?: T;
  bloodPercent?: T;
  owner?: T;
  herd?: T;
  author?: T;
  publicVisible?: T;
  publicDetails?: T;
  photo?: T;
  notes?: T;
  ipc?: T;
  ipcDetails?:
    | T
    | {
        forecast?: T;
        r?: T;
        percentile?: T;
      };
  evaluationDate?: T;
  production?:
    | T
    | {
        reliabilityLevel?: T;
        milk?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        fatPercent?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        proteinPercent?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        fatKg?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        proteinKg?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        productionIndex?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  reproduction?:
    | T
    | {
        fertility?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  health?:
    | T
    | {
        reliabilityLevel?: T;
        productiveLongevity?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        udderHealth?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        calfMortality?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
        calvingEase?:
          | T
          | {
              forecast?: T;
              r?: T;
            };
      };
  exterior?:
    | T
    | {
        height?: T;
        chestWidth?: T;
        bodyDepth?: T;
        bodyType?: T;
        rumpAngle?: T;
        rumpWidth?: T;
        rearLegsRear?: T;
        rearLegsSide?: T;
        hoofAngle?: T;
        frontLegs?: T;
        movement?: T;
        foreUdder?: T;
        frontTeatPlacement?: T;
        teatLength?: T;
        udderDepth?: T;
        rearUdder?: T;
        centralLigament?: T;
        rearTeatPlacement?: T;
        bodyComposite?: T;
        udderComposite?: T;
        legsComposite?: T;
      };
  summary?:
    | T
    | {
        milkYield?: T;
        fatPercent?: T;
        proteinPercent?: T;
        fatKg?: T;
        proteinKg?: T;
        fatProteinSum?: T;
      };
  lactations?:
    | T
    | {
        number?: T;
        calvingDate?: T;
        inseminationDate?: T;
        serviceBull?: T;
        dd?: T;
        milkYield?: T;
        milk305?: T;
        fat305?: T;
        protein305?: T;
        scc?: T;
        dryOffDate?: T;
        id?: T;
      };
  father?: T;
  mother?: T;
  pedigreeText?:
    | T
    | {
        fatherId?: T;
        fatherName?: T;
        motherId?: T;
        motherName?: T;
        fatherFatherId?: T;
        motherFatherId?: T;
      };
  inbreeding?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  type?: T;
  date?: T;
  animal?: T;
  title?: T;
  value?: T;
  comment?: T;
  status?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  title?: T;
  type?: T;
  number?: T;
  issuedAt?: T;
  animal?: T;
  organization?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}